export const MESSAGE_CONTENT_MAX_LENGTH = 2000;
export const MESSAGE_CONTENT_MIN_LENGTH = 1;

export const CHAT_MESSAGES_DEFAULT_PAGE = 1;
export const CHAT_MESSAGES_DEFAULT_LIMIT = 50;
export const CHAT_MESSAGES_MAX_LIMIT = 100;
