import {
  AlertTriangle,
  CheckCircle2,
  CircleDot,
  Info,
  ShieldCheck,
} from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import {
  getAreaLabel,
  OVERALL_CONDITION_LABELS,
  SEVERITY_LABELS,
} from '@/constants/photo-lock.constants';
import { formatDateTime } from '@/lib/format-date';
import { cn } from '@/lib/utils';
import type {
  PhotoLockChangeSeverity,
  PhotoLockComparison,
  PhotoLockOverallCondition,
} from '@/types/photo-lock.types';

const CONDITION_STYLES: Record<PhotoLockOverallCondition, string> = {
  good: 'bg-emerald-100 text-emerald-800 border-emerald-200',
  fair: 'bg-amber-100 text-amber-800 border-amber-200',
  disputed: 'bg-red-100 text-red-800 border-red-200',
};

const SEVERITY_STYLES: Record<PhotoLockChangeSeverity, string> = {
  none: 'text-emerald-700',
  minor: 'text-amber-700',
  significant: 'text-red-700',
};

function FindingIcon({ severity }: { severity: PhotoLockChangeSeverity }) {
  if (severity === 'none') {
    return <CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-600" />;
  }
  if (severity === 'minor') {
    return <CircleDot className="h-5 w-5 shrink-0 text-amber-600" />;
  }
  return <AlertTriangle className="h-5 w-5 shrink-0 text-red-600" />;
}

interface ComparisonReportProps {
  comparison: PhotoLockComparison;
}

export function ComparisonReport({ comparison }: ComparisonReportProps) {
  const condition = comparison.overallCondition;

  return (
    <Card className="border-indigo-200/70 bg-gradient-to-b from-indigo-50/70 via-background to-violet-50/30 shadow-sm">
      <CardHeader className="pb-3">
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div className="flex items-center gap-2">
            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-indigo-600 text-white shadow-sm">
              <ShieldCheck className="h-5 w-5" />
            </div>
            <div>
              <CardTitle className="text-lg">Condition comparison report</CardTitle>
              {comparison.comparedAt ? (
                <p className="text-sm text-muted-foreground">
                  Compared {formatDateTime(comparison.comparedAt)}
                </p>
              ) : null}
            </div>
          </div>
          {condition ? (
            <Badge
              variant="outline"
              className={cn('text-sm font-semibold', CONDITION_STYLES[condition])}
            >
              {OVERALL_CONDITION_LABELS[condition]}
            </Badge>
          ) : null}
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        {comparison.findings.length === 0 ? (
          <p className="text-sm text-muted-foreground">No findings were recorded.</p>
        ) : (
          <ul className="space-y-3">
            {comparison.findings.map((finding) => (
              <li
                key={`${finding.area}-${finding.severity}`}
                className="flex items-start gap-3 rounded-lg border border-border/80 bg-background/80 px-4 py-3"
              >
                <FindingIcon severity={finding.severity} />
                <div className="min-w-0 flex-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <p className="font-semibold">{getAreaLabel(finding.area)}</p>
                    <span
                      className={cn(
                        'text-xs font-medium uppercase tracking-wide',
                        SEVERITY_STYLES[finding.severity]
                      )}
                    >
                      {SEVERITY_LABELS[finding.severity]}
                    </span>
                  </div>
                  <p className="mt-1 text-sm text-muted-foreground">{finding.description}</p>
                </div>
              </li>
            ))}
          </ul>
        )}

        <div className="flex items-start gap-2 rounded-lg border border-indigo-100 bg-indigo-50/60 px-3 py-2.5 text-sm text-indigo-900">
          <Info className="mt-0.5 h-4 w-4 shrink-0" />
          <p>This comparison is generated by our AI review system.</p>
        </div>
      </CardContent>
    </Card>
  );
}
